kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
spec:
  persistentVolumeReclaimPolicy: "Retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

